wandb_version: 1

num_non_terminals:
  desc: null
  value: 4
max_productions:
  desc: null
  value: 1000
criterion:
  desc: null
  value: f1
num_sentences_per_score:
  desc: null
  value: 256
num_sentences_per_batch:
  desc: null
  value: 256
episodes_per_batch:
  desc: null
  value: 8
n_updates_per_iteration:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0002
gamma:
  desc: null
  value: 0.99
clip:
  desc: null
  value: 0.2
actor_weight:
  desc: null
  value: 1.0
critic_weight:
  desc: null
  value: 0.5
entropy_weight:
  desc: null
  value: 0.01
save_freq:
  desc: null
  value: 20
seed:
  desc: null
  value: 0
min_ep_rews_threshold:
  desc: null
  value: 0.0
hidden_dim:
  desc: null
  value: 512
n_layer:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742815064.746981
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.11
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
