name: learning-pcfg
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch==2.6.0
      - numpy==2.1.3
      - numba==0.61.0
      - jsbeautifier==1.15.4
      - dataclasses-json==0.6.7
      - wandb==0.19.8