_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
actor_weight:
    value: 1
clip:
    value: 0.2
criterion:
    value: f1
critic_weight:
    value: 0.5
entropy_weight:
    value: 0.01
episodes_per_batch:
    value: 8
gamma:
    value: 0.99
hidden_dim:
    value: 512
lr:
    value: 0.0002
max_productions:
    value: 1000
min_ep_rews_threshold:
    value: 0
n_layer:
    value: 3
n_updates_per_iteration:
    value: 10
num_non_terminals:
    value: 4
num_sentences_per_batch:
    value: 256
num_sentences_per_score:
    value: 256
save_freq:
    value: 20
seed:
    value: 0
